name: Deploy Azure Button

on: push

jobs:
  add-azure-deploy-button:
    runs-on: ubuntu-latest
    outputs: 
      fileUpdated: ${{ steps.generate-deploy-button.outputs.fileUpdated }}
    steps:
    - uses: actions/checkout@v2

    - name: generate-deploy-button
      id: generate-deploy-button
      uses: wilfriedwoivre/action-deploy-azure-button@master
      

    - name: debug
      run: echo ${{ steps.generate-deploy-button.outputs.fileUpdated }}
  
  push-updates:
    runs-on: ubuntu-latest
    needs: generate-deploy-button
 
    steps:
    - name: push-update
      if: needs.generate-deploy-button.outputs.fileUpdated
      run: |
          git config --global user.name 'Gitub Action Bot'
          git config --global user.email 'wilfried.woivre@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am "Add Azure deploy button"
          git push

  debug-job:
    name: Debug run job
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"          
        
