name: Deploy Azure Button

on: [push, pull_request]

jobs:
  add-azure-deploy-button:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: generate-deploy-button
      id: generate-deploy-button
      uses: wilfriedwoivre/action-deploy-azure-button@master

    - name: debug
      run: echo "${{ steps.generate-deploy-button.outputs.fileUpdated }}"

    - name: push-update
      if: steps.generate-deploy-button.outputs.fileUpdated == 'true'
      run: |
          git config --global user.name 'Gitub Action Bot'
          git config --global user.email 'wilfried.woivre@users.noreply.github.com'
          git commit -am "Add Azure deploy button"
          git push
